# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb85c015d133557b7b4f05b2fe6e146fbfc89eb6e3f8163606ba7a85910877398b84f844d373c0e5a753ae4140437cf9d756bd838b13edceeafb3410a0834bd2
  github_api_key: <%= ENV["GITHUB_API"] %>

test:
  secret_key_base: 48147f5c5bd3a931f50ff8951e5aa25f22a66b85deac0b249a80d45b0b7bdaea43fae99f187edda2fccfa99738914235096ef093aeeb0dd27b5c27cb69daa85a
  github_api_key: <%= ENV["GITHUB_API"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github_api_key: <%= ENV["GITHUB_API"] %>
